### PR TITLE
Add initial author validation workflow

### PR DESCRIPTION
**Pull request by learn-more**
Here is the initial validator workflow.

Some things could be improved, but it serves as a starting point.

- [x] Add a license (I was thinking about the MIT license)
- [x] Clean up PR before merging (drop the test commits)

### CODE REVIEW

**Comment by learn-more** [comment]
Here is the build after the 1st commit (no mods changed yet, so the check step will be skipped):
image

Here is the build after the 2nd commit (edited my own mod):
image

And here is the build after the 3rd commit (edited a mod that is not mine):
image

Full build history:
https://github.com/ramensoftware/windhawk-mods/actions/workflows/author_validation.yml

**Comment by learn-more** [comment]
And the warning is now shown in the diff view:

image

**Comment by learn-more** [comment]
@m417z This thing still displays green:
image

Do you want this to also show a warning?
Also, feel free to push to this PR to test some stuff out, if you want to play around with it.

**Comment by m417z** [comment]
Looks great, and a good basis for other checks such as the file name matching the mod id (to also catch mistakes [like this](https://github.com/ramensoftware/windhawk-mods/pull/10#issuecomment-1107640496)).

> Do you want this to also show a warning?

Yes, I think that would be better, otherwise the warning is easier to miss.

**Comment by learn-more** [comment]
Now the check fails on this.
There was no option to make it into a warning, but at least it's clearly visible

**Comment by m417z** [comment]
Looks good, thanks. Is it ready to be merged?

**Comment by learn-more** [comment]
It should be, unless you want me to push some test commits first?

**Comment by m417z** [comment]
Thanks! That's fine, we'll test in production :)

**Pull request merged**
