### PR TITLE
classic right-click context menu (instead of win 11)

### PR DESCRIPTION
**Pull request by ttodua**
switches from win11 style to win10 style

screenshot

I understand that per se this mod is not a "hook" but i view Windhawk as a broader framework to apply customizations with any viable ways. (whatever possible for now. if you or someone have a dedicated time to do this with other ways, ok, but now this is the only mod that will do the job)

### CODE REVIEW

**Comment by m417z** [comment]
As you noted, ideally Windhawk mods shouldn't make permanent changes to the system. You can try hooking registry access instead, here's a mod that does that which can serve as an example: [Windows 10 taskbar on Windows 11](https://windhawk.net/mods/win10-taskbar-on-win11).

**Comment by ttodua** [comment]
@m417z I tried but can't make it work (not proficient in c++), would you have one min to give a more specific code on the fly, to achieve what this PR tries?

**Comment by m417z** [comment]
I have it on my list to create such a mod, but currently I have more high-priority tasks.

**Comment by ttodua** [comment]
is it optimal to have this current mod merged until you release better mod (then remove this mode), does that sound acceptable? if not, i will surely understand.

**Comment by m417z** [comment]
I'd rather not merge this mod as is. If you need help improving it, you can try asking for help on the [Windhawk Discord server](https://discord.com/servers/windhawk-923944342991818753).

**Comment by ttodua** [comment]
> I'd rather not merge this mod as is. If you need help improving it, you can try asking for help on the [Windhawk Discord server](https://discord.com/servers/windhawk-923944342991818753).

i've tried but no-one replied. 
it's pity that while PR is not damaging as is, and has some clear precautionary step (like "explicit need to enable/disable in settings) still does its job for users (and most windhawk users probably are not very newbies). windhawk could be more scalable if such PRs are approved (which actually work or uses any viable approach to achieve its goal), otherwise development could be pedalized .
anyway, decision yours, thanks for everything, keep it on 👍

**Comment by m417z** [comment]
I just published [Classic context menu on Windows 11](https://windhawk.net/mods/explorer-context-menu-classic).

**Comment by ttodua** [comment]
@m417z thanks!

**Pull request closed without merging**
