### PR TITLE
Add Fix Darkmode ListViews mod

### PR DESCRIPTION
**Pull request by Reabstraction**
This is a quick mod I wrote for use with Rectify11 that fixes SysListView32's

### CODE REVIEW

**Comment by m417z** [comment]
How about adding a short readme that explains in more detail what the mod does, preferably with screenshots?

**Comment by Reabstraction** [comment]
I'll have to set up a Windows 11 VM to do that
Which I'll do later this day after work

**Comment by Reabstraction** [comment]
@m417z I have added a basic description

**Comment by Reabstraction** [comment]
It's basic but I'm no writer

**Comment by WildByDesign** [comment]
@Reabstraction Great work.

If you don’t mind me asking, does this only affect Regedit (from your screenshot) or does this also affect other programs as well?

If other programs as well, could you let me know a few of them as examples?

Thank you. I am also a Rectify11 user so I’m just trying to get an idea of where all this may benefit my setup.

**Comment by Reabstraction** [comment]
It affects all programs @WildByDesign

Not many apps seem to use SysListView32 though

**Comment by WildByDesign** [comment]
Thank you

**Pull request merged**
