### PR TITLE
Taskbar Thumbnail Reorder v1.0.7

### PR DESCRIPTION
**Pull request by m417z**
* Added an online symbol cache mechanism as a temporary workaround for the unavailable Microsoft symbols. Currently, this makes the mod work on Windows 11 versions 22631.3447 and 22631.3527. For more details, refer to [the relevant blog post](https://ramensoftware.com/windhawk-and-symbol-download-errors).

### CODE REVIEW

**Comment by AndroidDeveloperLB** [comment]
Say, is this only for the thumbnails, or also for the tasks in case it's not grouped?
For example if there are multiple tasks of the same app, and I want to reorder them, would it let me?

**Comment by m417z** [comment]
@AndroidDeveloperLB Yes, the order of the grouped taskbar items is synchronized with the order of the thumbnails.

**Comment by AndroidDeveloperLB** [comment]
@m417z Doesn't seem to work. It moves the entire group.

Watch:
[2024-07-23_03-46-51.zip](https://github.com/user-attachments/files/16341396/2024-07-23_03-46-51.zip)

**Comment by m417z** [comment]
Moving items on the taskbar moves the entire group. Reordering thumbnails changes the order of the group on the taskbar, too, which is what I thought you were asking.

**Comment by AndroidDeveloperLB** [comment]
@m417z Sorry but I don't understand. I asked about dragging of tasks.
Are you saying that I can drag the thumbnails, which will also change order of tasks?
If so, for some reason it doesn't work for me, perhaps because of a combination of the mods I've chosen?
Only when "Customize the old taskbar on Windows 11" is turned off, it works, but even then with various glitches. 

Please check it out:

[Carnac_2024-07-23_10-51-56.zip](https://github.com/user-attachments/files/16345452/Carnac_2024-07-23_10-51-56.zip)

Can you please create a mod to change the order of the tasks by dragging the tasks themselves? It was possible using "7+ Taskbar Tweaker" in the past...

**Comment by m417z** [comment]
> Are you saying that I can drag the thumbnails, which will also change order of tasks?

Yes.

> Only when "Customize the old taskbar on Windows 11" is turned off, it works, but even then with various glitches.

Since you aren't using the old taskbar, you don't need to turn it on.

You can see on 00:50 that it works, you can re-order the items.

> Can you please create a mod to change the order of the tasks by dragging the tasks themselves? It was possible using "7+ Taskbar Tweaker" in the past...

I think that what you're looking for is the [Disable grouping on the taskbar](https://windhawk.net/mods/taskbar-grouping) mod.

**Comment by AndroidDeveloperLB** [comment]
> you don't need to turn it on
I don't think I enabled it. Was turned on when installed.

> You can see on 00:50 that it works, you can re-order the items.
I know. That's why I wrote "...it works, but even then with various glitches.".

About the "Disable grouping on the taskbar ", it doesn't seem to do anything at all, even if I try to change its settings and disable other relevant mods

**Comment by m417z** [comment]
From the description:

> Note: After enabling the mod, the relevant windows must be reopened to apply the grouping settings.

**Comment by m417z** [comment]
> What I have is already ungrouped, no?

What you have is what I call "grouped, not combined". Not a single button, but still stuck together - move together, have thumbnails together. The taskbar-grouping mod makes all items completely separated.

**Comment by AndroidDeveloperLB** [comment]
@m417z I see. In the past I had just "7+ Taskbar Tweaker" that had it all. Now I have multiple mods here.
Hopefully they will all work nicely together.

Thank you very much.

**Comment by m417z** [comment]
Having them as separate mods have advantages. For example, if one of the mods stops working, you can still use the other mods.

**Comment by AndroidDeveloperLB** [comment]
@m417z Most choices in life have advantages and disadvantages
:)

**Pull request merged**
