### PR TITLE
Add taskbar item width setting

### PR DESCRIPTION
**Pull request by dr-consit**
Add functionality to allow the configuration of taskbar item width.

Most of the code is lifted from the taskbar label mod.

This may render this mod incompatible with the label mod?

### CODE REVIEW

**Comment by imagicalFantasy** [comment]
I just tested it and it's work perfectly.

**Comment by dr-consit** [comment]
@Gravarty Can you maybe say something about your setup (windows version)/settings/other mods?

**Comment by Gravarty** [comment]
Windows 11 22H2 Moment 2 2261.1344

Dark Paint
Disable Immersive Context Menus
Middle Click to close on the taskbar
Non Immersive Taskbar Context Menu
Shrink Address Bar Height
Taskbar Clock Customization

Disabled:

Disable grouping on the taskbar
Taskbar height and icon size (Original)
Taskbar Labels for Windows 11

**Comment by dr-consit** [comment]
OK, can you try disabling all other mods to see if that makes a difference, and also send the configuration settings from "Taskbar height and icon size"?

**Comment by dr-consit** [comment]
@Gravarty Alright, I hadn't tested any kind of size reduction, only size increase.
I have added some settings, to allow you to adjust some settings on the start button specifically.
If you shrink the icon size, you can now set the start button alignment to "left" and reduce the padding. This should help with your issue.

**Comment by Gravarty** [comment]
Oh nice, thanks! It's a bit better now, but changing the padding value, the button continues to move to the right instead of the left. Maybe that's just a hard coded restriction in the taskbar? I know it's unusual to have such a small aligment these days, I still have a 1080p monitor where modern elements like the taskbar are just too big :D

Screenshot_2

**Comment by dr-consit** [comment]
Alrighty then, I have added a separate width setting for the start button.

**Comment by Gravarty** [comment]
Fantastic, that's much better, thanks! :D There's still a tiny problem where the highlight frame is still overlapping and not centered with the button.. but still much better than the default gigantic taskbar and icon spacing.. Thanks!

**Comment by m417z** [comment]
Thank you for the pull request @dr-consit. I'm not sure about having this functionality as part of the icon size mod, both because of the code duplication from the taskbar labels mod, and because of the potential incompatibility it introduces.

I made some basic improvements in the taskbar labels mod which allow to set a small item width and it will be applied to pinned items as well. I wrote several other thoughts about it here: https://github.com/ramensoftware/windhawk-mods/issues/45#issuecomment-1492958617

**Comment by imagicalFantasy** [comment]
> Alrighty then, I have added a separate width setting for the start button.

Thank for start button settings ! It's awesome !

**Comment by m417z** [comment]
I added an option to control the width of taskbar buttons in version 1.2 of the mod. The way I implemented it is different than what this pull request does - a small change which hooks the function that's used to retrieve the width. Since the change is small and simple, it's likely to be more robust and less likely to break with updates. A downside of this approach is that explorer has to be restarted to apply this option, which isn't ideal, but not too bad since it usually has to be done only during the first configuration.

I'm closing this pull request, since the feature is implemented, and it's not going to be merged in its current form in any case. If anything else is missing, let me know.

**Pull request closed without merging**
