### PR TITLE
Update PR validation to be more strict

### PR DESCRIPTION
**Pull request by learn-more**
As requested in #95

### CODE REVIEW

**Comment by learn-more** [comment]
@m417z This PR immediately shows how it works on other files.
I did only validate .cpp files on their contents, because parsing .ico files and the likes could give weird results.
Let me know if you want to drop that restraint and try to validate every file.

**Comment by m417z** [comment]
No need to parse non-`.wh.cpp` files, but let's warn about them, since there should only be a single `mods/<mod-id>.wh.cpp` file per submission. And generally, it would be best to have a validation follow the readme instructions as closely as possible, e.g. only one added/modified source file, no change in the author name, version is increased (if not a new mod).

**Comment by learn-more** [comment]
> No need to parse non-`.wh.cpp` files, but let's warn about them, since there should only be a single `mods/<mod-id>.wh.cpp` file per submission. And generally, it would be best to have a validation follow the readme instructions as closely as possible, e.g. only one added/modified source file, no change in the author name, version is increased (if not a new mod).

* Every file that is not in the mods folder will generate a warning
* Every file that ends with `.cpp` will be inspected 'as mod'
* Every mod that will be inspected needs to have the full extension `.wh.cpp`

I'll add a validation that warns if there is more than one file changed.

**Comment by ItsProfessional** [comment]
Maybe add a check that compiles the mod and fails if error

**Comment by m417z** [comment]
Thanks

**Pull request merged**
