### PR TITLE
Center titlebar 1.0

### PR DESCRIPTION
**Pull request by rounk-ctrl**
wincentertitle's port

### CODE REVIEW

**Comment by m417z** [comment]
How about adding a message similar to this:
https://github.com/ramensoftware/windhawk-mods/blob/f4942e9c7cba28ea5fa515307e4dd843969a7902/mods/dwm-ghost-mods.wh.cpp#L30-L40

Also, how about screenshots? You can quickly upload them to Imgur.

**Comment by rounk-ctrl** [comment]
isnt the title self explanatory?

**Comment by m417z** [comment]
As a user, I'd like to see a screenshot. It's self-explanatory regarding what it does, not regarding how the result actually looks.

But I don't mind, it's only a suggestion, let me know when it's ready and I'll merge it.

**Comment by rounk-ctrl** [comment]
yeah done

**Pull request merged**
