### PR TITLE
Shrink Address Bar Height 1.0.0

### PR DESCRIPTION
**Pull request by ItsProfessional**
This mod shrinks the address bar height in file explorer.
Note: It hooks into every process, because if I only hook explorer.exe, it won't work on save/open dialogs.

### CODE REVIEW

**Comment by m417z** [comment]
> Note: It hooks into every process, because if I only hook explorer.exe, it won't work on save/open dialogs.

I think it's worth adding this to the readme.

**Comment by ItsProfessional** [comment]
Wouldn't that cause useless confusion? Many people will think that the mod is dangerous or some random nonsense because of that, and I'm not just making this up, I've seen this happen. Also, hooking into all programs is (hopefully) not a bad thing, [atleast according to the ExplorerPatcher dev](https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension):
> !!! IMPORTANT !!! Injecting in all process is no mean feat: that means most processes running on you system have this piece of code running into it. While I strive to provide clean and bug free releases, mistakes or problems may appear from time to time, and this has the potential of making more troublesome than usual to recover the system if something goes wrong, so beware before deciding towards using this.

**Comment by ItsProfessional** [comment]
Wait I've just realized that the screenshot is wrong, I'll fix that up

**Comment by ItsProfessional** [comment]
done

**Pull request merged**
